# 检测代码能否正常编译

name: BuildTest

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build artifact
        run: docker run --rm -v $PWD:/project -w /project espressif/idf:v4.4.2 idf.py build
