# 检测代码能否正常编译

name: BuildTest

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build artifact
        run: docker run --rm -v $PWD:/project -w /project espressif/idf:v4.4.2 bash -c "idf.py build && cd build && esptool.py --chip esp32c3 merge_bin -o esp32c3.bin @flash_args"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: esp32c3.bin
          path: ./build/esp32c3.bin